//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTPClient.WCFGetMsgHostService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFGetMsgHostService.IWCFGetHTTPMessageService")]
    public interface IWCFGetHTTPMessageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFGetHTTPMessageService/getPublicMessage", ReplyAction="http://tempuri.org/IWCFGetHTTPMessageService/getPublicMessageResponse")]
        string getPublicMessage(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFGetHTTPMessageService/getPublicMessage", ReplyAction="http://tempuri.org/IWCFGetHTTPMessageService/getPublicMessageResponse")]
        System.Threading.Tasks.Task<string> getPublicMessageAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFGetHTTPMessageServiceChannel : HTTPClient.WCFGetMsgHostService.IWCFGetHTTPMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFGetHTTPMessageServiceClient : System.ServiceModel.ClientBase<HTTPClient.WCFGetMsgHostService.IWCFGetHTTPMessageService>, HTTPClient.WCFGetMsgHostService.IWCFGetHTTPMessageService {
        
        public WCFGetHTTPMessageServiceClient() {
        }
        
        public WCFGetHTTPMessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFGetHTTPMessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFGetHTTPMessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFGetHTTPMessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getPublicMessage(string name) {
            return base.Channel.getPublicMessage(name);
        }
        
        public System.Threading.Tasks.Task<string> getPublicMessageAsync(string name) {
            return base.Channel.getPublicMessageAsync(name);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFGetMsgHostService.IWCFGetTCPMessageService")]
    public interface IWCFGetTCPMessageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFGetTCPMessageService/getPrivateMessage", ReplyAction="http://tempuri.org/IWCFGetTCPMessageService/getPrivateMessageResponse")]
        string getPrivateMessage(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFGetTCPMessageService/getPrivateMessage", ReplyAction="http://tempuri.org/IWCFGetTCPMessageService/getPrivateMessageResponse")]
        System.Threading.Tasks.Task<string> getPrivateMessageAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFGetTCPMessageServiceChannel : HTTPClient.WCFGetMsgHostService.IWCFGetTCPMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFGetTCPMessageServiceClient : System.ServiceModel.ClientBase<HTTPClient.WCFGetMsgHostService.IWCFGetTCPMessageService>, HTTPClient.WCFGetMsgHostService.IWCFGetTCPMessageService {
        
        public WCFGetTCPMessageServiceClient() {
        }
        
        public WCFGetTCPMessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFGetTCPMessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFGetTCPMessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFGetTCPMessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getPrivateMessage(string name) {
            return base.Channel.getPrivateMessage(name);
        }
        
        public System.Threading.Tasks.Task<string> getPrivateMessageAsync(string name) {
            return base.Channel.getPrivateMessageAsync(name);
        }
    }
}
